export const enumCategorie = [
    "Acessório para Carro",
    "Adaptador",
    "Apple",
    "Balança",
    "Baseus",
    "Basike",
    "Bateria",
    "Bluetooth",
    "Cabo",
    "Caixa de Som",
    "Campainha",
    "Carregador",
    "Celular",
    "Clone",
    "Digital",
    "Exbom",
    "Fone de Ouvido",
    "Idea",
    "Inova",
    "Lâmpada",
    "Led",
    "LG",
    "Manutenção do windows",
    "Microscópio",
    "Microsoft",
    "Motorola",
    "Mouse",
    "MousePad",
    "Multímetro",
    "Office",
    "Pilhas",
    "Power Bank",
    "Relógio Digital",
    "Samsung",
    "Sem Fio",
    "Suporte de Tv",
    "Teclado",
    "Tela",
    "Tela Frontal",
    "Troca de Bateria",
    "TV",
    "Tv Box",
    "USB",
    "Windows",
    "Xiaomi",
    "Zenfone",
    "Camisa",
];

export const enumManutence = [
    "Tela Frontal",
    "Bateria",
    "Apple Watch",
    "Tablet",
    "Ipad",
];

export const enumManutenceBrand = [
    "Nokia",
    "OnePlus",
    "Honor",
    "Realme",
    "Infinix",
    "Xiaomi",
    "Apple",
    "Samsung",
    "samsung",
    "Motorola",
    "LG",
    "MI",
    "REDMI",
    "NOTE",
];

export const enumModeProduct = ["Físico", "Digital"];
